#!/usr/bin/env python3
"""
Phone → Desktop AI Agent Dispatcher
=====================================
Telegram bot that routes commands to AI agents on your desktop.

Workflow:
  1. proj              — pick an active project directory
  2. claude: <prompt>  — run Claude Code in active project
     cursor: <prompt>  — run Cursor in active project
  3. gh pull           — git pull (authenticated)
     gh push           — git add -A, Claude-generated commit msg, push
     gh reset          — pick a commit to reset to
     gh init <url>     — git init + set remote origin

.env (next to this script):
  GITHUB_TOKEN=ghp_...
  GITHUB_EMAIL=you@example.com
  GITHUB_NAME=Your Name     # optional, defaults to email prefix

Other:
  mkdir: <name> [--public|--private]  — create dir (optionally as GitHub repo)
  status
"""

import asyncio
import json
import logging
import os
import platform
import re
import stat
import sys
import tempfile
from datetime import datetime
from pathlib import Path

CONFIG_PATH = Path(__file__).parent / "config.json"
ENV_PATH    = Path(__file__).parent / ".env"


def load_config():
    if not CONFIG_PATH.exists():
        print(f"ERROR: {CONFIG_PATH} not found. Copy config.example.json → config.json")
        sys.exit(1)
    with open(CONFIG_PATH) as f:
        return json.load(f)


def load_env_file() -> dict:
    result = {}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                result[k.strip()] = v.strip().strip('"').strip("'")
    return result


CFG              = load_config()
TELEGRAM_TOKEN   = CFG["telegram_bot_token"]
ALLOWED_CHAT_IDS = set(CFG.get("allowed_chat_ids", []))
MACHINE_NAME     = CFG.get("machine_name", platform.node())
WORK_DIR         = Path(CFG.get("default_work_dir", str(Path.home())))
MAX_OUTPUT_LEN   = CFG.get("max_output_length", 3500)
# Chat to receive permission requests (first allowed_chat_id, or explicit notify_chat_id)
NOTIFY_CHAT_ID   = CFG.get("notify_chat_id") or next(iter(sorted(ALLOWED_CHAT_IDS)), None)

_ENV             = load_env_file()
GITHUB_TOKEN     = _ENV.get("GITHUB_TOKEN", "")
GITHUB_EMAIL     = _ENV.get("GITHUB_EMAIL", "")
GITHUB_NAME      = _ENV.get("GITHUB_NAME", GITHUB_EMAIL.split("@")[0] if GITHUB_EMAIL else "bot")

logging.basicConfig(level=logging.INFO,
                    format=f"[{MACHINE_NAME}] %(asctime)s %(levelname)s: %(message)s")
log = logging.getLogger(__name__)

# Per-chat state
active_dirs: dict = {}  # chat_id → abs path str
pending:     dict = {}  # chat_id → {"type": "proj"|"reset"|"init", ...}

ALIASES = {"cc": "claude", "cur": "cursor", "github": "gh", "p": "proj"}

# ---------------------------------------------------------------------------
# Session persistence  (chat_id, work_dir) → claude session_id
# ---------------------------------------------------------------------------

SESSIONS_PATH = Path(__file__).parent / "sessions.json"


def _load_sessions() -> dict:
    if SESSIONS_PATH.exists():
        try:
            raw = json.loads(SESSIONS_PATH.read_text())
            return {(int(k.split("|", 1)[0]), k.split("|", 1)[1]): v
                    for k, v in raw.items()}
        except Exception:
            return {}
    return {}


def _save_sessions(sessions: dict):
    try:
        raw = {f"{k[0]}|{k[1]}": v for k, v in sessions.items()}
        SESSIONS_PATH.write_text(json.dumps(raw, indent=2))
    except Exception as e:
        log.warning(f"Could not save sessions: {e}")


sessions: dict = _load_sessions()

# ---------------------------------------------------------------------------
# Claude permission hook — forwards unknown tool requests to Telegram
# ---------------------------------------------------------------------------

# Tools auto-approved without prompting (matches --allowedTools passed to claude)
_CLAUDE_ALLOWED_TOOLS = (
    "Bash,Read,Write,Edit,Glob,Grep,LS,"
    "WebFetch,WebSearch,"
    "NotebookRead,NotebookEdit,"
    "TodoRead,TodoWrite"
)


def setup_claude_hooks():
    """
    Write permission_hook.py and register it as a Claude Code PreToolUse hook.
    The hook auto-approves tools in _CLAUDE_ALLOWED_TOOLS; for anything else it
    sends a Telegram message with Allow/Deny buttons and waits for the tap.
    Communication with the dispatcher uses temp files (/tmp/claude_perm_<id>.*).
    """
    if not NOTIFY_CHAT_ID:
        log.warning("No notify_chat_id configured — Claude permission hook disabled.")
        return

    hook_path = Path(__file__).parent / "permission_hook.py"
    allowed_set = "{" + ",".join(f'"{t.strip()}"' for t in _CLAUDE_ALLOWED_TOOLS.split(",")) + "}"

    hook_script = f'''#!/usr/bin/env python3
"""Claude Code PreToolUse permission hook — auto-generated by dispatcher.py"""
import json, os, sys, time, urllib.request, uuid

ALLOWED = {allowed_set}

data      = json.load(sys.stdin)
tool      = data.get("tool_name", "")
tool_in   = json.dumps(data.get("tool_input", {{}}), indent=2)[:400]

if tool in ALLOWED:
    print(json.dumps({{"decision": "approve"}}))
    sys.exit(0)

TOKEN   = "{TELEGRAM_TOKEN}"
CHAT_ID = {NOTIFY_CHAT_ID}

req_id    = uuid.uuid4().hex[:8]
req_file  = f"/tmp/claude_perm_{{req_id}}.request"
resp_file = f"/tmp/claude_perm_{{req_id}}.response"
open(req_file, "w").close()

payload = json.dumps({{
    "chat_id": CHAT_ID,
    "text": f"🔐 *Permission Request*\\n\\nTool: `{{tool}}`\\n```\\n{{tool_in}}\\n```",
    "parse_mode": "Markdown",
    "reply_markup": {{"inline_keyboard": [[
        {{"text": "✅ Allow", "callback_data": f"perm_allow:{{req_id}}"}},
        {{"text": "❌ Deny",  "callback_data": f"perm_deny:{{req_id}}"}}
    ]]}}
}}).encode()

try:
    urllib.request.urlopen(urllib.request.Request(
        f"https://api.telegram.org/bot{{TOKEN}}/sendMessage",
        data=payload, headers={{"Content-Type": "application/json"}}), timeout=10)
except Exception as e:
    os.unlink(req_file)
    print(json.dumps({{"decision": "deny", "reason": f"Telegram unreachable: {{e}}"}}))
    sys.exit(0)

for _ in range(30):
    time.sleep(2)
    if os.path.exists(resp_file):
        decision = open(resp_file).read().strip()
        os.unlink(resp_file)
        os.unlink(req_file)
        print(json.dumps({{"decision": "approve" if decision == "allow" else "deny",
                           "reason": "" if decision == "allow" else "Denied via Telegram"}}))
        sys.exit(0)

os.unlink(req_file)
print(json.dumps({{"decision": "deny", "reason": "Permission request timed out (60s)"}}))
'''

    hook_path.write_text(hook_script)
    hook_path.chmod(0o755)

    # Merge into ~/.claude/settings.json, preserving any existing settings
    settings_path = Path.home() / ".claude" / "settings.json"
    settings_path.parent.mkdir(exist_ok=True)
    try:
        settings = json.loads(settings_path.read_text()) if settings_path.exists() else {}
    except Exception:
        settings = {}

    settings.setdefault("hooks", {})
    settings["hooks"]["PreToolUse"] = [{
        "matcher": ".*",
        "hooks": [{"type": "command", "command": f"python3 {hook_path}"}]
    }]
    settings_path.write_text(json.dumps(settings, indent=2))
    log.info(f"Claude permission hook registered → {hook_path}")


# ---------------------------------------------------------------------------
# Git auth via GIT_ASKPASS helper script
# ---------------------------------------------------------------------------

def _make_askpass():
    """Write a GIT_ASKPASS script that reads creds from env vars. Returns path."""
    if not GITHUB_TOKEN:
        return None
    try:
        fd, path = tempfile.mkstemp(suffix=".sh", prefix="git_askpass_")
        with os.fdopen(fd, "w") as f:
            f.write('#!/bin/sh\n'
                    'case "$1" in\n'
                    '  *Username*) echo "$_GIT_USER" ;;\n'
                    '  *)          echo "$_GIT_PASS" ;;\n'
                    'esac\n')
        os.chmod(path, stat.S_IRWXU)
        return path
    except Exception as e:
        log.warning(f"Could not create askpass script: {e}")
        return None


ASKPASS = _make_askpass()

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def list_subdirs() -> list:
    try:
        return sorted(d.name for d in WORK_DIR.iterdir()
                      if d.is_dir() and not d.name.startswith("."))
    except Exception:
        return []


def parse_message(text: str):
    """Returns (cmd, args). Normalises aliases and strips trailing colon."""
    text = text.strip()
    if not text:
        return "", ""
    parts = text.split(None, 1)
    cmd  = parts[0].lower().rstrip(":")
    args = parts[1].strip() if len(parts) > 1 else ""
    return ALIASES.get(cmd, cmd), args


def truncate(text: str) -> str:
    return text[:MAX_OUTPUT_LEN] + "\n… (truncated)" if len(text) > MAX_OUTPUT_LEN else text


def git_id_flags() -> list:
    """Return git -c flags for user identity, if configured."""
    if GITHUB_EMAIL:
        return ["-c", f"user.email={GITHUB_EMAIL}", "-c", f"user.name={GITHUB_NAME}"]
    return []


async def _git(cmd: list, work_dir: str, timeout: int = 60, env=None) -> str:
    # GIT_CEILING_DIRECTORIES stops git traversing above work_dir to find a .git
    _env = {**(env if env is not None else os.environ),
            "GIT_CEILING_DIRECTORIES": str(Path(work_dir).parent)}
    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd, stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE, cwd=work_dir, env=_env)
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=timeout)
        out = stdout.decode(errors="replace").strip()
        err = stderr.decode(errors="replace").strip()
        if proc.returncode != 0:
            return (f"{out}\n{err}" if out else err) or f"[exit {proc.returncode}]"
        return out or "(done)"
    except asyncio.TimeoutError: return f"⏱ timed out ({timeout}s)"
    except FileNotFoundError:    return "❌ `git` not found"
    except Exception as e:       return f"❌ {e}"


async def _git_auth(cmd: list, work_dir: str, timeout: int = 60) -> str:
    """Run a git command with GitHub token authentication via GIT_ASKPASS."""
    if not ASKPASS or not GITHUB_TOKEN:
        return await _git(cmd, work_dir, timeout)
    env = {
        **os.environ,
        "GIT_TERMINAL_PROMPT": "0",
        "GIT_ASKPASS":         ASKPASS,
        "_GIT_USER":           GITHUB_EMAIL,
        "_GIT_PASS":           GITHUB_TOKEN,
    }
    return await _git(cmd, work_dir, timeout, env=env)


async def fetch_recent_commits(work_dir: str, n: int = 8) -> list:
    out = await _git(["git", "log", "--pretty=format:%h|%s", f"-{n}"], work_dir)
    commits = []
    for line in out.splitlines():
        if "|" in line:
            h, msg = line.split("|", 1)
            commits.append({"hash": h.strip(), "msg": msg.strip()[:50]})
    return commits


async def generate_commit_message(diff: str) -> str:
    """Ask Claude to write a one-line commit message for the staged diff."""
    prompt = (
        "Write a concise git commit message (one line, max 72 chars) summarising "
        "these changes. Output ONLY the commit message — no quotes, no explanation.\n\n"
        + diff[:4000]
    )
    try:
        proc = await asyncio.create_subprocess_exec(
            "claude", "-p", prompt, "--output-format", "text",
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE)
        stdout, _ = await asyncio.wait_for(proc.communicate(), timeout=30)
        msg = stdout.decode(errors="replace").strip().strip('"').strip("'")
        return msg or f"Update {datetime.now():%Y-%m-%d %H:%M}"
    except Exception:
        return f"Update {datetime.now():%Y-%m-%d %H:%M}"

# ---------------------------------------------------------------------------
# Agent runners
# ---------------------------------------------------------------------------

async def run_claude(prompt: str, work_dir: str, chat_id: int = 0) -> str:
    session_key = (chat_id, work_dir)
    session_id  = sessions.get(session_key)

    cmd = ["claude", "-p", prompt, "--output-format", "json",
           "--allowedTools", _CLAUDE_ALLOWED_TOOLS]
    if session_id:
        cmd += ["--resume", session_id]

    log.info(f"Claude in {work_dir} (session: {session_id or 'new'}): {prompt[:60]}")
    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd, stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE, cwd=work_dir)
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=900)
        raw = stdout.decode(errors="replace").strip()

        # JSON output may be a single object or JSONL — find the result line
        result = ""
        for line in reversed(raw.splitlines()):
            line = line.strip()
            if not line.startswith("{"):
                continue
            try:
                data = json.loads(line)
                if "result" in data:
                    result = data["result"] or ""
                    sid = data.get("session_id")
                    if sid:
                        sessions[session_key] = sid
                        _save_sessions(sessions)
                    break
            except json.JSONDecodeError:
                continue

        return result or f"[exit {proc.returncode}] {stderr.decode(errors='replace').strip()}"
    except asyncio.TimeoutError: return "⏱ Claude timed out (15m)"
    except FileNotFoundError:    return "❌ `claude` not found"
    except Exception as e:       return f"❌ {e}"


async def run_cursor(prompt: str, work_dir: str) -> str:
    cmd = ["agent", "chat", "--yolo", prompt]
    log.info(f"Cursor in {work_dir}: {prompt[:60]}")
    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd, stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE, cwd=work_dir)
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=900)
        out = stdout.decode(errors="replace").strip()
        return out or f"[exit {proc.returncode}] {stderr.decode(errors='replace').strip()}"
    except asyncio.TimeoutError: return "⏱ Cursor timed out (15m)"
    except FileNotFoundError:    return "❌ `agent` (Cursor CLI) not found"
    except Exception as e:       return f"❌ {e}"


async def run_gh(subcmd: str, work_dir: str) -> str:
    parts = subcmd.split(None, 1)
    op  = parts[0].lower() if parts else ""
    arg = parts[1].strip() if len(parts) > 1 else ""

    if op == "pull":
        return await _git_auth(["git", "pull"], work_dir)

    if op == "push":
        status = await _git(["git", "status", "--porcelain"], work_dir)
        if not status.strip():
            return "Nothing to commit — working tree clean."

        await _git(["git", "add", "-A"], work_dir)

        diff, stat = await asyncio.gather(
            _git(["git", "diff", "--staged"],         work_dir),
            _git(["git", "diff", "--staged", "--stat"], work_dir),
        )

        msg = await generate_commit_message(diff)
        await _git(["git"] + git_id_flags() + ["commit", "-m", msg], work_dir)
        push = await _git_auth(["git", "push", "-u", "origin", "HEAD"], work_dir)

        lines = [f"📝 _{msg}_", stat, push]
        return "\n\n".join(l for l in lines if l and l != "(done)")

    if op == "reset" and arg:
        return await _git(["git", "reset", "--hard", arg], work_dir)

    # "reset" without hash is handled in handle_message (shows picker)
    return f"❌ Unknown: `{op}`. Use: pull · push · reset · init <url>"


async def run_gh_init(url: str, work_dir: str) -> str:
    """git init + configure identity + set remote origin."""
    parts = []

    # Init if not already a repo (use --git-dir so it doesn't traverse up)
    gitdir = await _git(["git", "rev-parse", "--git-dir"], work_dir)
    if gitdir.startswith("❌") or "fatal" in gitdir:
        await _git(["git", "init"], work_dir)
        parts.append("Initialised git repo")
    else:
        parts.append("Already a git repo")

    # Set identity
    if GITHUB_EMAIL:
        await _git(["git", "config", "user.email", GITHUB_EMAIL], work_dir)
        await _git(["git", "config", "user.name",  GITHUB_NAME],  work_dir)
        parts.append(f"Identity: {GITHUB_EMAIL}")

    # Add or update remote origin
    remotes = (await _git(["git", "remote"], work_dir)).splitlines()

    verb = "set-url" if "origin" in remotes else "add"
    await _git(["git", "remote", verb, "origin", url], work_dir)
    parts.append(f"Remote origin → {url}")

    return "✅ " + "\n".join(parts)


async def run_mkdir(args: str, work_dir: str) -> str:
    parts = args.strip().split()
    if not parts:
        return "❌ Usage: `mkdir: <name> [--public|--private]`"
    name  = parts[0]
    flags = parts[1:]
    if not re.match(r'^[\w.\-]+$', name):
        return f"❌ Invalid name: `{name}`"
    new_dir = Path(work_dir) / name
    try:
        new_dir.mkdir(parents=True, exist_ok=False)
    except FileExistsError:
        return f"❌ Already exists: `{new_dir}`"
    except Exception as e:
        return f"❌ {e}"

    visibility = ("--public"  if "--public"  in flags else
                  "--private" if "--private" in flags else None)
    if not visibility:
        return f"✅ Created `{new_dir}`"

    (new_dir / "README.md").write_text(f"# {name}\n")
    for cmd in (["git", "init"],
                ["git"] + git_id_flags() + ["add", "README.md"],
                ["git"] + git_id_flags() + ["commit", "-m", "Initial commit"]):
        await _git(cmd, str(new_dir))

    try:
        proc = await asyncio.create_subprocess_exec(
            "gh", "repo", "create", name, visibility,
            "--source=.", "--remote=origin", "--push",
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
            cwd=str(new_dir))
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=60)
        out = stdout.decode(errors="replace").strip()
        err = stderr.decode(errors="replace").strip()
        if proc.returncode != 0:
            return f"✅ Dir + git init done\n❌ `gh repo create` failed:\n{err or out}"
        return f"✅ `{name}` created + GitHub repo ({visibility[2:]})\n{out}"
    except asyncio.TimeoutError: return "✅ Dir created, `gh repo create` timed out"
    except FileNotFoundError:    return "✅ Dir + git init done (`gh` CLI not found)"
    except Exception as e:       return f"✅ Dir created, `gh repo create` failed: {e}"

# ---------------------------------------------------------------------------
# Telegram bot
# ---------------------------------------------------------------------------

async def main():
    from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
    from telegram.ext import (Application, MessageHandler, CommandHandler,
                               CallbackQueryHandler, filters, ContextTypes)

    app = Application.builder().token(TELEGRAM_TOKEN).build()

    def authorized(update: Update) -> bool:
        return not ALLOWED_CHAT_IDS or update.effective_chat.id in ALLOWED_CHAT_IDS

    async def handle_start(update: Update, context: ContextTypes.DEFAULT_TYPE):
        auth = "✅ token loaded" if GITHUB_TOKEN else "⚠️ no token \\(.env\\)"
        await update.message.reply_text(
            f"🖥 *{MACHINE_NAME}* ready  \\(GitHub: {auth}\\)\n\n"
            f"1\\. `proj` — pick a project\n"
            f"2\\. `claude: prompt` / `cursor: prompt`\n"
            f"3\\. `gh pull` / `gh push` / `gh reset` / `gh init <url>`\n\n"
            f"`mkdir: name \\[\\-\\-public|\\-\\-private\\]`\n"
            f"`status`",
            parse_mode="MarkdownV2"
        )

    async def handle_status(update: Update, context: ContextTypes.DEFAULT_TYPE):
        if not authorized(update):
            return
        wd   = active_dirs.get(update.effective_chat.id)
        proj = f"`{Path(wd).name}`" if wd else "_(none)_"
        auth = f"`{GITHUB_EMAIL}`" if GITHUB_EMAIL else "_(not configured)_"
        await update.message.reply_text(
            f"🖥 *{MACHINE_NAME}*  {platform.system()} {platform.release()}\n"
            f"📂 `{WORK_DIR}`\n"
            f"📌 Active: {proj}\n"
            f"🔑 GitHub: {auth}\n"
            f"⏰ {datetime.now():%H:%M:%S}",
            parse_mode="Markdown"
        )

    async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
        chat_id = update.effective_chat.id
        if not authorized(update):
            await update.message.reply_text(
                f"⛔ Unauthorized. Chat ID: `{chat_id}`", parse_mode="Markdown")
            return

        text = (update.message.text or "").strip()

        # ── Intercept pending "init" waiting for a URL ──────────────────────
        p = pending.get(chat_id, {})
        if p.get("type") == "init":
            url = text
            pending.pop(chat_id)
            if url.startswith("http"):
                ack = await update.message.reply_text("⏳ Initialising…")
                result = await run_gh_init(url, p["work_dir"])
                await ack.edit_text(result)
            else:
                await update.message.reply_text("❌ Doesn't look like a URL. Run `gh init` again.")
            return

        cmd, args = parse_message(text)

        if cmd == "status":
            await handle_status(update, context)
            return

        # ── proj ─────────────────────────────────────────────────────────────
        if cmd == "proj":
            subdirs = list_subdirs()
            if not subdirs:
                await update.message.reply_text(
                    f"No subdirectories found in `{WORK_DIR}`.", parse_mode="Markdown")
                return
            pending[chat_id] = {"type": "proj", "subdirs": subdirs}
            rows = ([[InlineKeyboardButton(
                         f"/ {WORK_DIR.name}/ (root)", callback_data="proj:0")]] +
                    [[InlineKeyboardButton(f"📁 {d}", callback_data=f"proj:{i+1}")]
                     for i, d in enumerate(subdirs)])
            await update.message.reply_text("📂 Select project:",
                                            reply_markup=InlineKeyboardMarkup(rows))
            return

        # ── commands requiring an active project ─────────────────────────────
        wd = active_dirs.get(chat_id)
        if cmd in ("claude", "cursor", "gh") and not wd:
            await update.message.reply_text(
                "📂 No active project. Send `proj` to pick one.", parse_mode="Markdown")
            return

        if cmd == "claude":
            if not args:
                await update.message.reply_text("Usage: `claude: <prompt>`", parse_mode="Markdown")
                return
            # claude new — clear session for this project
            if args.strip().lower() == "new":
                sessions.pop((chat_id, wd), None)
                _save_sessions(sessions)
                await update.message.reply_text(
                    f"🔄 Claude session cleared for `{Path(wd).name}`.", parse_mode="Markdown")
                return
            ack = await update.message.reply_text(
                f"⏳ Claude in `{Path(wd).name}`…", parse_mode="Markdown")
            result = truncate(await run_claude(args, wd, chat_id))
            sid = sessions.get((chat_id, wd))
            header = f"✅ *{MACHINE_NAME}* — Claude (`{Path(wd).name}`)"
            header += f"  _{sid[:8]}_" if sid else ""
            try:
                await ack.edit_text(f"{header}\n\n{result}", parse_mode="Markdown")
            except Exception:
                await ack.edit_text(f"✅ {MACHINE_NAME} — Claude\n\n{result}")
            return

        if cmd == "cursor":
            if not args:
                await update.message.reply_text("Usage: `cursor: <prompt>`", parse_mode="Markdown")
                return
            ack = await update.message.reply_text(
                f"⏳ Cursor in `{Path(wd).name}`…", parse_mode="Markdown")
            result = truncate(await run_cursor(args, wd))
            try:
                await ack.edit_text(
                    f"✅ *{MACHINE_NAME}* — Cursor (`{Path(wd).name}`)\n\n{result}",
                    parse_mode="Markdown")
            except Exception:
                await ack.edit_text(f"✅ {MACHINE_NAME} — Cursor\n\n{result}")
            return

        if cmd == "gh":
            op = args.split()[0].lower() if args.split() else ""

            # gh init — with or without URL
            if op == "init":
                url = args.split(None, 1)[1].strip() if len(args.split(None, 1)) > 1 else ""
                if url:
                    ack = await update.message.reply_text("⏳ Initialising…")
                    result = await run_gh_init(url, wd)
                    await ack.edit_text(result)
                else:
                    pending[chat_id] = {"type": "init", "work_dir": wd}
                    await update.message.reply_text(
                        "🔗 Paste your GitHub repo URL:\n"
                        "_(e.g. `https://github.com/you/repo.git`)_",
                        parse_mode="Markdown")
                return

            # gh reset without hash → commit picker
            if op == "reset" and not args.split()[1:]:
                commits = await fetch_recent_commits(wd)
                if not commits:
                    await update.message.reply_text("No commits found in this repo.")
                    return
                pending[chat_id] = {"type": "reset", "work_dir": wd, "commits": commits}
                rows = [[InlineKeyboardButton(
                            f"{c['hash']} — {c['msg']}", callback_data=f"reset:{i}")]
                        for i, c in enumerate(commits)]
                await update.message.reply_text("↩️ Reset to which commit?",
                                                reply_markup=InlineKeyboardMarkup(rows))
                return

            label = f"gh {op}" if op else "gh"
            ack = await update.message.reply_text(
                f"⏳ {label} in `{Path(wd).name}`…", parse_mode="Markdown")
            result = truncate(await run_gh(args, wd))
            try:
                await ack.edit_text(
                    f"✅ *{MACHINE_NAME}* — {label} (`{Path(wd).name}`)\n\n{result}",
                    parse_mode="Markdown")
            except Exception:
                await ack.edit_text(f"✅ {MACHINE_NAME} — {label}\n\n{result}")
            return

        if cmd == "mkdir":
            ack = await update.message.reply_text("⏳ Creating…")
            result = await run_mkdir(args, str(WORK_DIR))
            await ack.edit_text(result)
            return

        if cmd:
            await update.message.reply_text(
                f"Unknown: `{cmd}`. Send /start for help.", parse_mode="Markdown")

    async def handle_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
        query = update.callback_query
        await query.answer()
        if not authorized(update):
            return

        chat_id = update.effective_chat.id
        data    = query.data or ""

        if data.startswith("proj:"):
            p       = pending.pop(chat_id, {})
            subdirs = p.get("subdirs", [])
            idx     = int(data[5:])
            if idx == 0:
                active_dirs[chat_id] = str(WORK_DIR)
                name = f"{WORK_DIR.name}/ (root)"
            else:
                name = subdirs[idx - 1]
                active_dirs[chat_id] = str(WORK_DIR / name)
            await query.edit_message_text(f"📌 Active project: *{name}*", parse_mode="Markdown")

        elif data.startswith("reset:"):
            p = pending.pop(chat_id, None)
            if not p:
                await query.edit_message_text("⚠️ Session expired. Run `gh reset` again.")
                return
            idx    = int(data[6:])
            commit = p["commits"][idx]
            result = await _git(["git", "reset", "--hard", commit["hash"]], p["work_dir"])
            await query.edit_message_text(
                f"↩️ Reset to `{commit['hash']}` — {commit['msg']}\n\n{result}",
                parse_mode="Markdown")

        elif data.startswith("perm_allow:") or data.startswith("perm_deny:"):
            req_id    = data.split(":", 1)[1]
            decision  = "allow" if data.startswith("perm_allow:") else "deny"
            req_file  = f"/tmp/claude_perm_{req_id}.request"
            resp_file = f"/tmp/claude_perm_{req_id}.response"
            if os.path.exists(req_file):
                with open(resp_file, "w") as f:
                    f.write(decision)
                icon = "✅" if decision == "allow" else "❌"
                await query.edit_message_text(
                    f"{icon} {decision.title()}ed permission `{req_id}`")
            else:
                await query.edit_message_text(
                    f"⚠️ Request `{req_id}` already resolved or expired.")

    async def handle_media(update: Update, context: ContextTypes.DEFAULT_TYPE):
        chat_id = update.effective_chat.id
        if not authorized(update):
            return

        msg = update.message
        caption = (msg.caption or "").strip()
        wd = active_dirs.get(chat_id)
        if not wd:
            await msg.reply_text(
                "📂 No active project. Send `proj` to pick one first.", parse_mode="Markdown")
            return

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        if msg.photo:
            file_id    = msg.photo[-1].file_id
            filename   = f"photo_{timestamp}.jpg"
            media_type = "photo"
        elif msg.video:
            file_id    = msg.video.file_id
            filename   = f"video_{timestamp}.mp4"
            media_type = "video"
        elif msg.video_note:
            file_id    = msg.video_note.file_id
            filename   = f"videonote_{timestamp}.mp4"
            media_type = "video"
        elif msg.document and msg.document.mime_type and \
                msg.document.mime_type.startswith("image/"):
            file_id    = msg.document.file_id
            ext        = (msg.document.file_name or "image.jpg").rsplit(".", 1)[-1]
            filename   = f"image_{timestamp}.{ext}"
            media_type = "photo"
        else:
            return

        save_path = Path(wd) / filename
        ack = await msg.reply_text(f"⏳ Downloading {media_type}…")

        try:
            tg_file = await context.bot.get_file(file_id)
            await tg_file.download_to_drive(str(save_path))
        except Exception as e:
            await ack.edit_text(f"❌ Download failed: {e}")
            return

        if media_type == "video":
            frames_dir = Path(wd) / f"frames_{timestamp}"
            frames_dir.mkdir(exist_ok=True)
            frame_files = []
            try:
                proc = await asyncio.create_subprocess_exec(
                    "ffmpeg", "-i", str(save_path), "-vf", "fps=1",
                    str(frames_dir / "frame_%03d.jpg"),
                    stdout=asyncio.subprocess.DEVNULL, stderr=asyncio.subprocess.DEVNULL)
                await asyncio.wait_for(proc.communicate(), timeout=120)
                frame_files = sorted(frames_dir.glob("frame_*.jpg"))
            except Exception:
                pass

            if frame_files:
                frames_list = "\n".join(f"`{f}`" for f in frame_files[:12])
                prompt = (
                    f"{caption}\n\n" if caption else ""
                ) + (
                    f"I sent you a video. I extracted frames (1 per second) saved in `{frames_dir}/`. "
                    f"Use the Read tool to view these frame images and describe what you see:\n{frames_list}"
                )
            else:
                prompt = (
                    f"{caption}\n\n" if caption else ""
                ) + (
                    f"I sent you a video saved at `{save_path}`. "
                    f"Note: ffmpeg frame extraction was unavailable. Describe the file if possible."
                )
        else:
            prompt = (
                f"{caption}\n\n" if caption else "Analyze this image. "
            ) + f"Use the Read tool to view and describe the image at `{save_path}`."

        await ack.edit_text(
            f"⏳ Claude analyzing {media_type} in `{Path(wd).name}`…", parse_mode="Markdown")
        result = truncate(await run_claude(prompt, wd, chat_id))
        sid    = sessions.get((chat_id, wd))
        header = f"✅ *{MACHINE_NAME}* — Vision (`{Path(wd).name}`)"
        header += f"  _{sid[:8]}_" if sid else ""
        try:
            await ack.edit_text(f"{header}\n\n{result}", parse_mode="Markdown")
        except Exception:
            await ack.edit_text(f"✅ {MACHINE_NAME} — Vision\n\n{result}")

    app.add_handler(CommandHandler("start", handle_start))
    app.add_handler(CommandHandler("status", handle_status))
    app.add_handler(CallbackQueryHandler(handle_callback))
    app.add_handler(MessageHandler(
        (filters.PHOTO | filters.VIDEO | filters.VIDEO_NOTE | filters.Document.IMAGE)
        & ~filters.COMMAND,
        handle_media))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))

    setup_claude_hooks()

    auth_status = f"GitHub: {GITHUB_EMAIL}" if GITHUB_EMAIL else "GitHub: not configured"
    log.info(f"🚀 {MACHINE_NAME} ({platform.system()}), work dir: {WORK_DIR}")
    log.info(f"🔒 Allowed: {ALLOWED_CHAT_IDS or 'ALL'}  |  {auth_status}")

    await app.initialize()
    await app.start()
    await app.updater.start_polling()
    try:
        await asyncio.Event().wait()
    except (KeyboardInterrupt, SystemExit):
        log.info("Shutting down…")
        if ASKPASS:
            try:
                os.unlink(ASKPASS)
            except Exception:
                pass
        await app.updater.stop()
        await app.stop()
        await app.shutdown()


if __name__ == "__main__":
    asyncio.run(main())
